export const codigos_espejo = [
  {
    nombre: "PDVAL AMAZONAS",
    codigo: "891932",
    estado: "Amazonas",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL ANZOATEGUI",
    codigo: "891933",
    estado: "Anzoátegui",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL APURE",
    codigo: "891935",
    estado: "Apure",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL ARAGUA",
    codigo: "897899",
    estado: "Aragua",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL BARINAS",
    codigo: "897901",
    estado: "Barinas",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL BOLIVAR",
    codigo: "891937",
    estado: "Bolívar",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL CARABOBO",
    codigo: "897923",
    estado: "Carabobo",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL COJEDES",
    codigo: "897975",
    estado: "Cojedes",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL DELTA AMACURO",
    codigo: "897940",
    estado: "Delta Amacuro",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL DISTRITO CAPITAL",
    codigo: "897946",
    estado: "Distrito Capital",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL FALCON",
    codigo: "897949",
    estado: "Falcón",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL GUARICO",
    codigo: "897955",
    estado: "Guárico",
    entidad: "PDVAL",
  },
  { nombre: "PDVAL LARA", codigo: "897957", estado: "Lara", entidad: "PDVAL" },
  {
    nombre: "PDVAL MERIDA",
    codigo: "897960",
    estado: "Mérida",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL MIRANDA",
    codigo: "897961",
    estado: "Miranda",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL MONAGAS",
    codigo: "897967",
    estado: "Monagas",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL NUEVA ESPARTA",
    codigo: "891939",
    estado: "Nueva Esparta",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL PORTUGUESA",
    codigo: "897963",
    estado: "Portuguesa",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL SUCRE",
    codigo: "897966",
    estado: "Sucre",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL TACHIRA",
    codigo: "897970",
    estado: "Táchira",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL TRUJILLO",
    codigo: "897972",
    estado: "Trujillo",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL LA GUAIRA",
    codigo: "897973",
    estado: "La Guaira",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL YARACUY",
    codigo: "897974",
    estado: "Yaracuy",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL ZULIA",
    codigo: "891940",
    estado: "Zulia",
    entidad: "PDVAL",
  },
  {
    nombre: "PDVAL AMAZONAS",
    codigo: "898020",
    estado: "Amazonas",
    entidad: "PDVAL",
  },
  {
    nombre: "MERCAL APURE",
    codigo: "897993",
    estado: "Apure",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL ARAGUA",
    codigo: "897996",
    estado: "Aragua",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL BARINAS",
    codigo: "897998",
    estado: "Barinas",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL CARABOBO",
    codigo: "897999",
    estado: "Carabobo",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL COJEDES",
    codigo: "898001",
    estado: "Cojedes",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL DELTA AMACURO",
    codigo: "898003",
    estado: "Delta Amacuro",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL TAZON",
    codigo: "898004",
    estado: "Distrito Capital",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL FALCON",
    codigo: "898005",
    estado: "Falcón",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL GUARICO",
    codigo: "898006",
    estado: "Guárico",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL LARA",
    codigo: "898007",
    estado: "Lara",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL MERIDA LAGUNILLA",
    codigo: "898009",
    estado: "Mérida",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL MIRANDA EL TAMBOR",
    codigo: "898010",
    estado: "Miranda",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL MONAGAS TEJERO",
    codigo: "898011",
    estado: "Monagas",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL PORTUGUESA",
    codigo: "898012",
    estado: "Portuguesa",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL SUCRE",
    codigo: "898013",
    estado: "Sucre",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL TACHIRA",
    codigo: "898015",
    estado: "Táchira",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL TRUJILLO",
    codigo: "898016",
    estado: "Trujillo",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL LA GUAIRA",
    codigo: "898018",
    estado: "La Guaira",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL YARACUY",
    codigo: "898019",
    estado: "Yaracuy",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL MERIDA LIBERTADOR",
    codigo: "898023",
    estado: "Mérida",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL MIRANDA EL LLANITO",
    codigo: "898025",
    estado: "Miranda",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL AMAZONAS",
    codigo: "891941",
    estado: "Amazonas",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL ANZOATEGUI",
    codigo: "891944",
    estado: "Anzoátegui",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL BOLIVAR",
    codigo: "891945",
    estado: "Bolívar",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL NUEVA ESPARTA",
    codigo: "891946",
    estado: "Nueva Esparta",
    entidad: "Mercal",
  },
  {
    nombre: "MERCAL ZULIA",
    codigo: "891947",
    estado: "Zulia",
    entidad: "Mercal",
  },
  {
    nombre: "CAMSA MIRANDA",
    codigo: "898421",
    estado: "Miranda",
    entidad: "CAMSA",
  },
  {
    nombre: "RED DE ABASTOS BICENTENARIO DISTRITO CAPITAL",
    codigo: "898425",
    estado: "Distrito Capital",
    entidad: "RABSA",
  },
  {
    nombre: "INTEGRAL DE MERCADOS Y ALMACENES COCHE",
    codigo: "899032",
    estado: "Distrito Capital",
    entidad: "IMAC",
  },
  {
    nombre: "RECDIAL S.A. PORTUGUESA",
    codigo: "898092",
    estado: "Portuguesa",
    entidad: "RECDIAL",
  },
  {
    nombre: "SOBERANIA PATRIOTA C.A. MONAGAS",
    codigo: "898422",
    estado: "Monagas",
    entidad: "Soberanía Patriota",
  },
  {
    nombre: "LACTEOS LOS ANDES, C.A. (ESTADO ZULIA)",
    codigo: "972605",
    estado: "Zulia",
    entidad: "Lacteos Los Andes",
  },
  {
    nombre: "ALIMENTOS CARABOBO C.A. ALIMCA C.A.",
    codigo: "973715",
    estado: "Carabobo",
    entidad: "ALIMCA",
  },
  {
    nombre: "GOBERNACION LARA (ABASTLARA)",
    codigo: "902267",
    estado: "Lara",
    entidad: "Gobernación Lara",
  },
  {
    nombre: "CEALCO VALENCIA",
    codigo: "467918",
    estado: "Carabobo",
    entidad: "CEALCO",
  },
  {
    nombre: "CEALCO CAGUA CONGELADOS",
    codigo: "617214",
    estado: "Aragua",
    entidad: "CEALCO",
  },
  {
    nombre: "CEALCO CAGUA REFRIGERADOS",
    codigo: "415450",
    estado: "Aragua",
    entidad: "CEALCO",
  },
  {
    nombre: "CEALCO BARINAS",
    codigo: "223689",
    estado: "Barinas",
    entidad: "CEALCO",
  },
  {
    nombre: "FRIGORIFICO TAZON",
    codigo: "875656",
    estado: "Distrito Capital",
    entidad: "Frigorífico Tazón",
  },
  {
    nombre: "CEALCO BARCELONA",
    codigo: "440796",
    estado: "Anzoátegui",
    entidad: "CEALCO",
  },
  {
    nombre: "CEALCO LA MORITA",
    codigo: "42292",
    estado: "Aragua",
    entidad: "CEALCO",
  },
];
